services:
  docker_dev:
    image: 0xee/my_docker_aio:latest
    container_name: my_docker_aio
    ports:
      - "81:80"
      - "5433:5432"
    volumes:
      - ./nginx:/etc/nginx
      - ./html:/var/www/html
      - ./postgresql:/etc/postgresql/16/main
      - ./php:/etc/php/8.3
      - ./supervisor:/etc/supervisor
      - ./start_service.sh:/myDocker/start_service.sh
    command: ["/bin/bash", "/myDocker/start_service.sh"]
    restart: unless-stopped
